<a href="https://colab.research.google.com/github/Barkalounger/hello-world/blob/main/Pain_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# !pip install yfinance --upgrade --no-cache-dir

import yfinance as yf

msft = yf.Ticker("MSFT")
msft.financials

                                       2020-06-30  ... 2017-06-30
Research Development                         None  ...       None
Effect Of Accounting Charges                 None  ...       None
Income Before Tax                            None  ...       None
Minority Interest                            None  ...       None
Net Income                                      0  ...          0
Selling General Administrative               None  ...       None
Gross Profit                                    0  ...          0
Ebit                                            0  ...          0
Operating Income                             None  ...       None
Other Operating Expenses                     None  ...       None
Interest Expense                             None  ...       None
Extraordinary Items                          None  ...       None
Non Recurring                                None  ...       None
Other Items                                  None  ...       None
Income Tax Expense                              0  ...          0
Total Revenue                                   0  ...          0
Total Operating Expenses                        0  ...          0
Cost Of Revenue                                 0  ...          0
Total Other Income Expense Net                  0  ...          0
Discontinued Operations                      None  ...       None
Net Income From Continuing Ops               None  ...       None
Net Income Applicable To Common Shares       None  ...       None

[22 rows x 4 columns]